Update robot.yml

diff --git a/.github/workflows/robot.yml b/.github/workflows/robot.yml
--- a/.github/workflows/robot.yml
+++ b/.github/workflows/robot.yml
@@ -1,49 +1,57 @@
-# runs tests for push-events, for pull requests and using cron schedule:
 name: Run Robot Framework Tests
 on:
-  push:
-    # runs tests for commits pushed to master
+  pull_request:
     branches:
       - master
-    # do not run tests if file README.md changes
-    paths-ignore:
-      - '**.md'
-    # run tests for GitHub Pull requests. Test result is visible in the Pull Request page.
-  pull_request:
-    paths-ignore:
-      - '**.md'
-  schedule:
-    # run tests once a year in January 1st
-    - cron:  '0 0 1 1 *'
+
 jobs:
-    run_tests:
-        runs-on: ubuntu-latest
-        steps:
-        # checkout code from a repository
-        - uses: actions/checkout@v3
-        # create folder for test reports
-        - name: Create folder for reports
-          run: mkdir reports
-        # run Robot Framework tests inside Docker container
-        - name: Run Robot Framework Tests
-          # container used here is ppodgorsek/robot-framework:latest
-          # it is strongly recommended to use versioned image (ie. not the tag latest like here) to maintain dependencies
-          # see container documentation for usage: https://hub.docker.com/r/ppodgorsek/robot-framework/dockerfile
-          # it is required that GitHub repository contains folder "reports". Commit some file inside "reports" to create it
-          # place tests in folder tests or change docker run command accordingly
-          # configure -e ROBOT_OPTIONS according to yout tests, or remove it if no special configuration is needed
-          run: |
-            docker run \
-              -v ${PWD}/reports:/opt/robotframework/reports:Z \
-              -v ${PWD}/tests:/opt/robotframework/tests:Z \
-              -e ROBOT_OPTIONS="--variable DINOSAUR:Achillobator --variable NOT_DINOSAUR:kissa" \
-              --user $(id -u):$(id -g) \
-              ppodgorsek/robot-framework:latest
-        # upload test reports as a zip file
-        - name: Upload reports
-          uses: actions/upload-artifact@v3
-          if: always()
-          with:
-            name: reports
-            # set path to Robot Framework results reports. Exclude dummy file that is needed because of ppodgorsek image priviledges.
-            path: ${{ github.workspace }}/reports
+  choose_action:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Request Action Input
+        id: choose_action
+        run: |
+          echo "::set-output name=selected_action::$(echo -e 'Action 1\nAction 2' | fzf)"
+
+  run_action:
+    needs: choose_action
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v3
+
+      - name: Create folder for reports
+        run: mkdir reports
+
+      - name: Run Selected Action
+        run: |
+          selected_action="${{ needs.choose_action.outputs.selected_action }}"
+          case $selected_action in
+            "Action 1")
+              docker run \
+                -v ${PWD}/reports:/opt/robotframework/reports:Z \
+                -v ${PWD}/tests:/opt/robotframework/tests:Z \
+                -e ROBOT_OPTIONS="--variable DINOSAUR:Achillobator --variable NOT_DINOSAUR:kissa" \
+                --user $(id -u):$(id -g) \
+                ppodgorsek/robot-framework:latest
+              ;;
+            "Action 2")
+              docker run \
+                -v ${PWD}/reports:/opt/robotframework/reports:Z \
+                -v ${PWD}/tests2:/opt/robotframework/tests2:Z \
+                -e ROBOT_OPTIONS="--variable DINOSAUR:Achillobator --variable NOT_DINOSAUR:kissa" \
+                --user $(id -u):$(id -g) \
+                ppodgorsek/robot-framework:latest
+              ;;
+            *)
+              echo "Invalid action selected"
+              exit 1
+              ;;
+          )
+
+      - name: Upload reports
+        uses: actions/upload-artifact@v3
+        if: always()
+        with:
+          name: reports
+          path: ${{ github.workspace }}/reports
